### ISSUE TITLE
Add option for opening in new tab/window

### ISSUE THREAD

**Issue by greeze** [stevehanson/domain-switcher-chrome#1]
Love the extension, thank you!  I'd love it if there were a way to open the clicked domain in a new tab or window.  I do this with bookmarks by using middle-click on Windows, or cmd-click on OSX, but a clickable icon would also work.  If I find some time, I'll try to put together a pull request, but I wanted to put this here in case someone else finds the time before I do.

Thank you again for such a useful extension!

**Comment by shovanco** [comment]
@stevehanson Hi , this is a great plugin. @greeze I dont see open in new window option in the setting.. can you help?

**Comment by greeze** [comment]
Hi @shovanuk! It's been a long time since I used this extension, but I don't think there ever was a setting for that. You just hold down `ctrl`, `alt`, or `cmd` when you click an environment.

**Comment by shovanco** [comment]
Thanks @greeze thats what I was doing, though there my be an option to open in new window by default
