### ISSUE TITLE
Sync settings via google cloud

### ISSUE THREAD

**Issue by amenk** [stevehanson/domain-switcher-chrome#10]
I am using a synced google account. Could the host settings be also stored in that account to be used across all browsers where I sign in?

**Comment by stevehanson** [comment]
Good idea. I'll try to get to that some time, or feel free to open a PR. The main challenge will just be around migrating existing users' data from local storage to Google Cloud.

Adding a link to the documentation for reference.: https://developer.chrome.com/apps/storage
