### ISSUE TITLE
Auto configuration of domains for a project by conventions

### ISSUE THREAD

**Issue by amenk** [stevehanson/domain-switcher-chrome#11]
We usually have environments like this:

example.com (LIVE)
example.com.testing.ourcompany.de (Public testing instance)

example.com.mycomputer.ourcompany.local

So it would be great if we could add this structure once as configuration and then have new domains we add automatically "inherit" this convention.

**Comment by amenk** [comment]
What do you think?

**Comment by stevehanson** [comment]
This sounds similar to https://github.com/stevehanson/domain-switcher-chrome/issues/5. I'm just not sure how to implement it without introducing complexity to the user interface. I'm open to suggestions, but the solution would have to work with other setups, like:

```
example.com.something.local
text.example.com
staging.example.com
example.com
```

```
example.dev
test.some-test-server.com
stage.some-test-server.com
example.com
```

It doesn't seem like we could automatically detect how this works, since there are so many ways environments can be set up. What would you propose the UI look like for setting this up?

**Comment by amenk** [comment]
Actually I think about templates.
Configuring something like  the following, where $ is the placeholder for the live domain

```
$
$.something.local
staging.$
```

So for adding a new project, I can choose "from template" and enter the live domain - we could even add it to the menu

**Comment by amenk** [comment]
I will try to implement it.

**Comment by amenk** [comment]
![screenshot_auswahl_016](https://cloud.githubusercontent.com/assets/1087128/15532208/d21ed5bc-225e-11e6-8a68-a1df93f0da48.png)
![screenshot_auswahl_015](https://cloud.githubusercontent.com/assets/1087128/15532211/d4616628-225e-11e6-8dfc-86a4644b5d6a.png)

**Comment by amenk** [comment]
I implemented... some small bugs concerning the edit mode.

**Comment by amenk** [comment]
No clue how I can call the option page's addProject from within the popup...

**Comment by stevehanson** [comment]
Thanks for looking into this, but I'm still concerned about this feature. As it stands right now, I feel like it adds too much complexity. We'd have to indicate which domains should use the template and which shouldn't, and there's the confusion of "what is a template?" when the user sees that button. I think I'd rather just keep it simple for now.

**Comment by amenk** [comment]
We can optimize the UI. But how? I think it is super useful. And it is a
Pro extension anyways

**Comment by stevehanson** [comment]
Good point on this being a pro/power-user extension.

Maybe if there's an "Advanced Options" section or something and a way to enable domain templates from there, we could have the best of both worlds. Will just need to think a bit on it.

**Comment by amenk** [comment]
The "complicated UI" only comes if you click "make template". I could add another hint if you click it. As it integrates like the other projects I would not say it complicates it too much.

**Comment by amenk** [comment]
Any more thoughts on this?

**Comment by amenk** [comment]
_bump_

**Comment by stevehanson** [comment]
I'm still hesitant on this one. I don't have a lot of time to work on this extension, and this seems like a complicated feature to do right. If this is something you need right now, you can always fork this repo and make the changes locally and install the extension locally. Sorry I can't make this happen right now.

**Comment by amenk** [comment]
I _did_ implement it already. But I am not fully happy about the UX, that is why I appreciate your comments. The fork is on github already, but I am interested in doing it right so it can be merged. Would rather not like so much to create an independent fork.

My new idea for the UX: Just one button "Add template" on the bottom, so the UI is not cluttered with the possibility to make everything a template (which also does not make so much sense - it's just because of the way the data is stored).

**Comment by amenk** [comment]
New UI:

![ui-first-step](https://cloud.githubusercontent.com/assets/1087128/17442396/e02ce350-5b35-11e6-85ac-85f055492cf1.png)
![ui-second-step](https://cloud.githubusercontent.com/assets/1087128/17442397/e1efb208-5b35-11e6-8e71-84aaf13bea23.png)

**Comment by stevehanson** [comment]
That looks nice. I'll try to take more time to look at it before long.

**Comment by amenk** [comment]
Before long :-)

**Comment by amenk** [comment]
Maybe this weekend :-) ?

**Comment by stevehanson** [comment]
As mentioned before, if you are anxious for this feature, you are welcome to run the extension locally with this feature. I don't have any estimate for when I get to this. It might be in a few weeks, or it might be in a year. This is a side project for me, and this feature was not solicited by me in any way. I do appreciate your contributions but also ask that you respect that I am busy and not devoting much time to this extension right now.

**Comment by amenk** [comment]
Okay, sure, I totally respect that. I just want also others to use and to
avoid to create a fork and distribute separately in the app store. Locally
I am already using it :) Sorry for nagging so much.

2016-09-02 16:06 GMT+02:00 Steve Hanson notifications@github.com:

**Comment by stevehanson** [comment]
No worries, totally get it.

Just checked out your branch to take a quick look. I'm a little confused about how the templates functionality works. Specifically, I see how to define a template, but I don't see how I can use the template definition for setting up an environment. Would you be able to help me figure that out or share a screenshot of what a configuration might look like with templates?

**Comment by amenk** [comment]
Always when you add a new project it should be asking for the live domain (example.com) and will then create the project. Also there is an "+ Add This" in the popup to quickly add when you are on the live site
![screenshot_auswahl_018](https://cloud.githubusercontent.com/assets/1087128/18207240/97b386d2-712a-11e6-80b2-6ce9dabdb1bf.png)
![screenshot_auswahl_019](https://cloud.githubusercontent.com/assets/1087128/18207267/c50eeb80-712a-11e6-999b-4e2535ab8ffe.png)

**Comment by stevehanson** [comment]
Oh gotcha. Makes sense now. Just commented on [your PR](https://github.com/stevehanson/domain-switcher-chrome/pull/15).

**Comment by stevehanson** [comment]
Discussion moving to PR #15

**Comment by amenk** [comment]
I forked the project and added my commits - in case this project becomes more active, I probably will remove my fork from the store ...
https://chrome.google.com/webstore/detail/domain-switcher-forked/obncmfopicdjkamflcoipkjdpkdhfjji
