### ISSUE TITLE
Color code the icon and menu entries by environment to choose more quickly

### ISSUE THREAD

**Issue by amenk** [stevehanson/domain-switcher-chrome#16]
- if I am on live: make  the switcher icon green
- if I am on my local dev machine: make it orange

and so on

**Comment by amenk** [comment]
my suggestion: We define a palette with around 10 colors, from "dangerous" to "not so dangerous".
We should recommend to the users to put the live site always first, so that will be the red one.
In case the live site is not "dangerous" for somebody, they can still decide to enter their domains in reverse order.

Shall I go for that?

**Comment by amenk** [comment]
_bump_

**Comment by stevehanson** [comment]
I'm not interested in doing this one.

**Comment by amenk** [comment]
I am not sure if you understand me right ... I would implement that.. Just expect your comments on the UX. I would rather not like to go for an independent fork, so I really appreciate your input. I think it would be a useful feature and I would make it inactive per default.

Please reopen if possible ;-)
