### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by amenk** [stevehanson/domain-switcher-chrome#19]
Did anybody try to port this to firefox? How hard would it be?

**Comment by amenk** [comment]
I tried to convert via chrome store foxified and sign by Firefox..
I am getting some errors:

    Banned 3rd-party JS library

    Error: Your add-on uses a JavaScript library we consider unsafe. Read more: https://bit.ly/1TRIyZY
    bower_components/angular/angular.min.js

-> just have to upgrade angular ...

But when enforcing usigned the installation using Firefox Dev edition, it is also not working (icon missing in the toolbar)

**Comment by Patabugen** [comment]
Did you have any more luck porting to Firefox?
